version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    links:
      - db
    env_file:
      - .env

  db:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.infra/mysql-db:/var/lib/mysql
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - "8000:80"
    links:
      - db
    env_file:
      - .env
